name: Blinky_Nucleo_H7A3
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  target-gcc-arm-none-eabi:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: update-tools
        run: sudo sudo apt-get update -y;sudo apt-get install -y gcc-arm-none-eabi;sudo apt-get install -y python3
      - name: target-gcc-arm-none-eabi
        run: |
          bash Rebuild.sh
          ls -la ./Output/Blinky_Nucleo_H7A3.hex
